name: marketing_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  vexana: ^3.1.1
  kartal: ^2.7.0
  sizer: ^2.0.15
  dio: ^4.0.6
  auto_route: ^5.0.4
  build_runner: ^2.3.2
  auto_route_generator: ^5.0.3
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  google_fonts: ^3.0.1
  auto_size_text: ^3.0.0
  salomon_bottom_bar: ^3.3.1
  font_awesome_flutter: ^10.2.1
  flutter_slidable: ^2.0.0
  flutter_image_slider: ^0.0.2
  flutter_image_slideshow: ^0.1.4
  flutter_bloc: ^8.1.1
  lottie: ^1.4.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
